TxnLab/use-wallet

package.json
src/clients/algosigner/client.ts
src/clients/algosigner/types.ts
src/clients/base/base.ts
src/clients/defly/client.ts
src/clients/defly/types.ts
src/clients/exodus/client.ts
src/clients/exodus/types.ts
src/clients/kmd/client.ts
src/clients/kmd/types.ts
src/clients/myalgo/client.ts
src/clients/myalgo/types.ts
src/clients/pera/client.ts
src/clients/pera/types.ts
src/clients/walletconnect/client.ts
src/clients/walletconnect/types.ts
src/hooks/useWallet.ts
src/types/wallet.ts
src/utils/clearAccounts.ts
src/utils/reconnectProviders.ts

- Prevent KMD from prompting password on app mount
- Fix a bug where default KMD configuration wasn't valid
- Fix a bug where providers would not disconnect if the session was killed in the wallet app (affected Defly and Pera).

Bug Fixes & Improvements

---

package.json
src/clients/walletconnect/client.ts

In the WalletConnect client's `signTransactions` method, signed transactions are merged back into the original transaction group and returned.
Previously we iterated over the payload returned by WalletConnect to create this array, now we iterate over the original group instead.
Each transaction's array index is checked against `signedIndexes`, containing the index of every transaction sent for signature. If there's a match, we swap it out for the signed transaction from the payload. If not, the original transaction is pushed to the result array.
(This follows the same pattern used in both the Pera and Defly clients.)
When complete, the new array is returned.
Closes https://github.com/TxnLab/use-wallet/issues/44

TXN-1274: Fix handling signed transactions in WalletConnect client

---

src/clients/walletconnect/client.ts

Some WalletConnect wallets return all transactions after signing, others only return the signed transactions. Now we handle both cases.

TXN-1276: Handle varying payload lengths in signTransactions

---

package.json
src/clients/algosigner/client.ts
src/clients/algosigner/types.ts
src/types/wallet.ts

AlgoSigner v1.10.0 introduces a new top-level object, `window.algorand`, with an updated API for connecting and signing transactions. Documentation: https://github.com/PureStake/algosigner/blob/develop/docs/dApp-integration.md
One of the new features is support for signing transactions with rekeyed accounts. The use-wallet AlgoSigner client now checks each connected account for a `'auth-addr'` property (indicating the account has been rekeyed), and saves this address as `authAddr` in the account object saved to the wallet store.
When transactions are marshalled to be signed, each unsigned transaction's `snd` (sender) account is checked for this `authAddr` property. If one is found, it's added to the transaction object before being sent for a signature.
> **Note**
> The user must import …

TXN-1277: Migrate to AlgoSigner v1.10.0, support rekeyed signing

---

src/clients/base/base.ts

The return type of `groupTransactionsBySender` in the base client was inadvertently changed in https://github.com/TxnLab/use-wallet/pull/52
This reverts it back to its original return type of `Record<string, Array<TxnInfo>>`

TXN-1283: Fix return type of groupTransactionsBySender

---

package.json
yarn.lock

Upgrades `@blockshake/defly-connect` and `@perawallet/connect` to latest versions, and removes `rollup-plugin-rename-node-modules`. This should resolve the errors on `npm install` reported in https://github.com/TxnLab/use-wallet/issues/54

TXN-1285: Fix dependency resolution errors using NPM

---

README.md
src/components/Example/Example.tsx
src/utils/initializeProviders.test.ts
src/utils/initializeProviders.ts

The `initializeProviders` utility function needs to be async, so we can await each client's async `init` method. Otherwise a race condition occurs and if the app mounts before initialization completes, `reconnectProviders` is called too early.
⚠️ **BREAKING CHANGE:** The exported `initializeProviders` function is now async and must be awaited and called from inside a `useEffect` hook. The README has been updated accordingly.

TXN-1292: Update initializeProviders to be async

---

package.json
src/clients/walletconnect/client.ts
src/clients/walletconnect/types.ts
yarn.lock

Peer dependencies used by wallet providers are set as optional, and dynamically imported in the client classes where they are used.
This also installs optional dependencies used by `@walletconnect/client` as devDependencies, to suppress errors when symlinking `@txnlab/use-wallet` for local development.
Closes #67

TXN-1107: Make provider dependencies optional

---

src/clients/base/base.ts
src/clients/daffi/client.ts
src/clients/defly/client.ts
src/clients/exodus/client.ts
src/clients/kmd/client.ts
src/clients/mnemonic/client.ts
src/clients/pera/client.ts
src/clients/walletconnect/client.ts

The `signTransactions` function returned by `useWallet` currently accepts only an array of encoded transactions, but it should also be able to handle a nested array (array of arrays).
Each client's `signTransactions` method now checks for a nested array and flattens it before decoding and marshaling the transactions for signature.

TXN-1398: Handle nested transaction arrays in signTransactions

---

src/hooks/useInitializeProviders.test.tsx
src/hooks/useInitializeProviders.ts

If used correctly, we can get away with `eslint-disable-next-line react-hooks/exhaustive-deps` for the dependency array.
It mirrors the original implementation being abstracted by the hook. Provider config and node config shouldn't be changing once initialization is successful.

TXN-1402: Fix infinite render loop in useInitializeProviders

---

src/constants/constants.ts
src/utils/initializeProviders.test.ts
src/utils/initializeProviders.ts

The default provider list still contained MyAlgo and AlgoSigner. Since the list of non-default providers is now longer than the list of defaults, the way they're filtered is also refactored.

TXN-1406: Fix default providers if none specified

---

README.md
__mocks__/walletconnect-client.js
__mocks__/walletconnect-modal.js
__mocks__/walletconnect-sign-client.js
__mocks__/walletconnect-utils.js
__mocks__/web3modal-sign-html.js
jest.config.ts
package.json
src/clients/walletconnect2/client.ts
src/clients/walletconnect2/types.ts
src/hooks/useInitializeProviders.test.tsx
src/hooks/useWallet.test.tsx
src/hooks/useWallet.ts
src/testUtils/mockClients.ts
src/types/providers.ts
yarn.lock

The @web3modal/sign-html client handles all of the @walletconnect/modal logic as well as lots of the complexity being handled manually in the previous WalletConnect provider client. And it's one peer dependency to install vs two.

TXN-1407: Replace @walletconnect/sign-client with @web3modal/sign-html

---

README.md
src/clients/daffi/client.ts
src/clients/defly/client.ts
src/clients/myalgo/client.ts
src/clients/pera/client.ts
src/clients/walletconnect2/client.ts
src/components/Example/Example.test.tsx
src/components/Example/Example.tsx
src/constants/constants.ts
src/hooks/useInitializeProviders.test.tsx
src/hooks/useInitializeProviders.ts
src/index.ts
src/types/providers.ts
src/types/utilities.ts
src/utils/initializeProviders.test.ts
src/utils/initializeProviders.ts

The cleanest, simplest solution to the build/compile errors encountered if any peer dependencies are not installed is to require static imports.
This is already a requirement for Remix, and it will ensure that only the necessary wallet SDK/client libraries need to be installed by consuming apps. This also removes the need for a "default configuration" and deciding which providers should or shouldn't belong in it. Every wallet provider will need to be passed to the `providers` property in `useInitializeProviders`, which is already how most apps do it.
**BREAKING CHANGE:** The `useInitializeProviders` hook must receive an object with the `providers` property defined. Provider objects passed to `providers` must include a `clientStatic` property set to the provider's SDK/client library, if it …

TXN-1412: Static imports are required

---

README.md
__mocks__/walletconnect-modal-sign-html.js
__mocks__/web3modal-sign-html.js
jest.config.ts
package.json
src/clients/walletconnect2/client.ts
src/clients/walletconnect2/types.ts
src/testUtils/mockClients.ts
src/types/providers.ts
yarn.lock

The deprecated @web3modal/sign-html peer dependency is replaced by @walletconnect/modal-sign-html.
This is a like-for-like change, except for the renamed exports. The client's methods/API are the same. The @walletconnect/modal-sign-html package uses a more recent version of @walletconnect/core than the deprecated @web3modal/sign-html.
**BREAKING CHANGE:** @web3modal/sign-html will no longer work

TXN-1408: Switch to @walletconnect/modal-sign-html

---

README.md
src/clients/daffi/client.ts
src/clients/defly/client.ts
src/clients/myalgo/client.ts
src/clients/pera/client.ts
src/clients/walletconnect2/client.ts
src/components/Example/Example.tsx
src/types/providers.ts

Prior to this change, each wallet library had to be imported statically, which greatly impacted the final build of a frontend due to the large size of these libraries.
With these changes, the possibility of dynamically importing these libraries is added in a backward compatible manner, and the developer can choose whether or not to opt for.
Specifically, the `getDynamicClient` parameter has been introduced. Users can incorporate this parameter into a provider's configuration. This parameter should be a function that returns a promise, which upon resolution, provides the corresponding wallet's client.
Currently, I haven't added any new unit tests since these would likely mock the implementation and thus, offer minimal benefit. Furthermore, considering the nature of the modification, the …

feat: enable dynamic import of wallet libraries

---

src/utils/initializeProviders.test.ts
src/utils/initializeProviders.ts

This is a fix for issue #104. With this fix, the order of the providers when passed into the `useInitializeProviders` hook will determine the order of providers in the `providers` array returned by the `useWallet` hook.

fix: preserve order of providers as passed into `useInitializeProviders`

---

README.md
src/clients/custom/client.ts

This updates the README to include a description of the Custom provider. It includes a general example and a link to the TestManualProvider in the Storybook example.

TXN-1540: Custom Provider documentation

---

src/clients/kmd/client.ts

This adds support for rekeyed signing to the kmd (Key Management Daemon) provider.
If a transaction in the group contains a `reKeyTo` property (and the specified account is connected) it is passed to kmd's `signTransactionWithSpecificPublicKey` method for signing.
Closes https://github.com/TxnLab/use-wallet/issues/120

feat: support rekeyed signing with kmd

---

src/clients/base/base.ts
src/clients/kibisis/client.ts
src/clients/kibisis/utils.test.ts
src/clients/kibisis/utils.ts

> _Please explain the changes you made here_
The use of [`crypto.randomUUID`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) does not work in non-secure contexts (only localhost HTTPS), which is causes HTTP environments to fail to load the Kibisis client. 
This fix attempts to polyfill this dependency by checking if the `crypto.randomUUID` exists and uses it, or uses a polyfill algorithm.

fix(kibisis): remove web crypto api dependency when generating uuid

---

src/clients/kibisis/constants.ts

> _Please explain the changes you made here_
Currently, when initializing the Kibisis client, a message is broadcast for discovery of the Kibisis that has a 3 second timeout. However, as the response should be quicker than this, the timeout is unnecessary long which blocks the initialization of other clients.
A 0.75 second timer provides a better compromise.

fix(kibisis): lower get provider timeout from 3 seconds to 0.75 seconds

---

README.md
src/clients/magic/client.ts
src/clients/magic/types.ts
src/components/Example/Example.tsx
src/testUtils/mockClients.ts
src/types/providers.ts

The library should not import any SDKs/dependencies for wallet providers (besides type imports). This should be handled by the consuming application on an opt-in basis, depending on which wallets it supports.
The Magic Algorand extension is now (optionally) passed to the `useInitializeProviders` hook's configuration object.
Closes #135

fix(magic): remove non-type Magic.link imports

---

src/clients/kibisis/utils.test.ts
src/clients/kibisis/utils.ts
yarn.lock

> _Please explain the changes you made here_
`global` was used to access the Web Crypto API to generate a UUID, but this only works in a Node.js environment and therefore throws a TypeError when run in a browser environment.
This fix changes the `global` reference to `window` to correctly reference the Web Crypto API in a browser environment.

fix(kibisis): replace global object with window

---

src/hooks/useWallet.ts
src/types/wallet.ts

- adds optional `throws` parameter to `connect` in order to react to connection errors

feat: add ability to throw connection errors

---

src/hooks/useWallet.ts

Consider this state:
Defly (active)
- Account A (active)
- Account B
Pera
- Account C
- Account D
If you try to set Account D as the active account, an error is thrown saying no matching account can be found. The reason is that it is only looking for connected accounts from the active provider. My change makes it so it looks through all connected accounts. This allows you to swap to any connected account with a single method call. (provider.setActiveAccount).
With the way that the tests are setup in useWallet.test.tsx, the activeAccount is hardcoded. What needs to be tested is that the activeAccount changes. I didn't want to make major changes to the test file, so I didn't implement any tests.

fix: allow any connected account to be set active

---

src/clients/kibisis/client.ts

There was a race condition where sometimes Kibisis wouldn't show up in the available providers. I believe this was happening because the channel was being created and a listener was being attached and then a message was immediately being posted. I've made a change so that the message being posted happens on the next tick so it actually gives the channel time to setup.
@kieranroneill

Fix: wrap postMessage in timeout to prevent race conditions

---

packages/use-wallet/src/wallets/base.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/exodus.ts
packages/use-wallet/src/wallets/kibisis.ts
packages/use-wallet/src/wallets/kmd.ts
packages/use-wallet/src/wallets/lute.ts
packages/use-wallet/src/wallets/mnemonic.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/walletconnect.ts

This converts `BaseWallet` public methods used as callbacks to arrow functions to preserve the `this` context across different usage scenarios.
In a React app passing `activeWallet.setActiveAccount` to a component as a prop, the wallet's `this.store` property was undefined. Converting `setActiveAccount` to an arrow function, along with any other methods being called in various (unpredictable) contexts, ensures that they operate with the intended scope.

fix(core): ensure correct `this` context in public callback methods

---

packages/use-wallet/package.json
packages/use-wallet/src/utils.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/exodus.ts
packages/use-wallet/src/wallets/kibisis.ts
packages/use-wallet/src/wallets/kmd.ts
packages/use-wallet/src/wallets/lute.ts
packages/use-wallet/src/wallets/mnemonic.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/walletconnect.ts
packages/use-wallet/tsconfig.json
pnpm-lock.yaml

Instead of requiring consuming applications to use the Node.js `Buffer` API polyfill to convert `Uint8Array` byte arrays to and from base 64 strings, wallet clients will now use native JavaScript methods `atob` and `btoa`.
Credit to PureStake, as utility functions for AlgoSigner were starting points for the functions now being used here: https://github.com/PureStake/algosigner/blob/master/packages/common/src/encoding.ts
I've also updated the core library's tsconfig to no longer enforce `noUncheckedIndexedAccess`, which forces me to use non-null assertion operators to access numbered array elements. This trade-off for the benefit it provides by strictly enforcing declared object properties doesn't seem worth it. I would've had to use it (again) in the `byteArrayToString` function. See …

fix(core): perform byte array <-> b64 conversions w/ native JS

---

packages/use-wallet/src/manager.ts

The WalletManager's `setActiveNetwork` method was missed when I was changing wallet client methods to arrow functions in https://github.com/TxnLab/use-wallet/pull/152
This (ha!) update ensures the correct `this` context is used when `setActiveNetwork` is passed as a callback to the framework adapters.

fix(ui): use correct `this` context in setActiveNetwork

---

package.json
src/clients/lute/client.ts
yarn.lock

There was a bug in the construction of `signedTxns` where it was expecting `result` to only contain txns that the wallet signed. Lute's response has the same length as the request, so `shift()` was not appropriate - a simple index on `result` will do.

fix(lute): fix signedTxns reconstruction

---

examples/solid-ts/src/Connect.tsx
packages/use-wallet-solid/src/useWallet.ts

The Solid adapter's two signing functions returned by `useWallet` –  `signTransactions` and `transactionSigner` – were using optional chaining to satisfy TypeScript and handle potentially null values for `activeWallet()`. But that meant the type signatures for those functions were a union including `| undefined`.
This removes the need for optional chaining by first assigning the `activeWallet()` return value to a variable and throwing an error if it is null.
To verify it works correctly, this PR also adds test transaction signing capabilities in the Solid example app.

fix(solid): fix transaction signing functions

---

packages/use-wallet-react/package.json
packages/use-wallet-solid/package.json
packages/use-wallet-vue/package.json
packages/use-wallet/package.json
pnpm-lock.yaml

Pins the following dependencies to their latest versions:
- `algosdk`
- `@tanstack/store`
- `@tanstack/react-store`
- `@tanstack/solid-store`
- `@tanstack/vue-store`

chore(deps): upgrade and pin all non-dev dependencies

---

README.md
packages/use-wallet/src/__tests__/wallets/custom.test.ts
packages/use-wallet/src/utils.ts
packages/use-wallet/src/wallets/custom.ts
packages/use-wallet/src/wallets/index.ts
packages/use-wallet/src/wallets/types.ts

Adds support for a custom wallet provider defined by the consuming application.
This feature was added to v2 by @robdmoore in https://github.com/TxnLab/use-wallet/pull/106 and has been adapted here for v3.
Closes #162

feat: add Custom provider

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

Upgraded to `pnpm@9.2.0` and re-installed dependencies, which updates `pnpm-lock.yaml` to the new lockfile version, `9.0`. The monorepo root `package.json` file now indicates this is the `packageManager` version that should be used.
While I was at it, this also updates the CI workflow to use Node 20 and the latest `pnpm/action-setup` version.

chore: upgrade to pnpm v9

---

packages/use-wallet/src/__tests__/wallets/walletconnect.test.ts
packages/use-wallet/src/wallets/walletconnect.ts

There are no restrictions or rules about the `algo_signTxn` RPC method response type. Each wallet can decide on its own how to format the signed transactions it returns.
(This should probably be spec'd or defined somewhere!)
The WalletConnect provider now handles numerous potential response types, to make sure it always returns an array of encoded signed transactions as `Promise<Uint8Array[]>`.
Its signing function response is now typed as
```ts
type SignTxnsResponse = Array<Uint8Array | string | null | undefined>
```

fix(walletconnect): handle all possible response types from algo_signTxn

---

README.md
examples/nextjs/package.json
examples/nextjs/src/app/providers.tsx
examples/nuxt/package.json
examples/nuxt/plugins/walletManager.client.ts
examples/react-ts/package.json
examples/react-ts/src/App.tsx
examples/solid-ts/package.json
examples/solid-ts/src/App.tsx
examples/vanilla-ts/package.json
examples/vanilla-ts/src/main.ts
examples/vue-ts/package.json
examples/vue-ts/src/main.ts
packages/use-wallet-react/package.json
packages/use-wallet-solid/package.json
packages/use-wallet-vue/package.json
packages/use-wallet/package.json
packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/__tests__/wallets/pera2.test.ts
packages/use-wallet/src/utils.ts
packages/use-wallet/src/wallets/pera2.ts
packages/use-wallet/src/wallets/types.ts
pnpm-lock.yaml

While the testing for the Pera Connect v2 beta so far has been very promising, due to an unresolved issue this reverts the default `PERA` provider back to Pera Connect v1.
A dependency of `@perawallet/connect-beta` – `@walletconnect/sign-client` – is not included in Vite production builds. Vite's dev mode uses esbuild and everything works fine, but for some reason the Rollup production builds omit the Sign client and an error is thrown when you try to connect.
Instead of removing the new provider, it will remain as an undocumented option, `PERA2`, so it can continue to be tested on an opt-in basis.

chore: revert Pera provider to Pera Connect v1

---

packages/use-wallet-react/src/index.tsx
packages/use-wallet-solid/src/index.tsx
packages/use-wallet-vue/src/useWallet.ts
packages/use-wallet/src/__tests__/wallets/defly.test.ts
packages/use-wallet/src/__tests__/wallets/exodus.test.ts
packages/use-wallet/src/__tests__/wallets/kibisis.test.ts
packages/use-wallet/src/__tests__/wallets/lute.test.ts
packages/use-wallet/src/__tests__/wallets/magic.test.ts
packages/use-wallet/src/__tests__/wallets/pera.test.ts
packages/use-wallet/src/__tests__/wallets/pera2.test.ts
packages/use-wallet/src/__tests__/wallets/walletconnect.test.ts
packages/use-wallet/src/wallets/base.ts
packages/use-wallet/src/wallets/custom.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/exodus.ts
packages/use-wallet/src/wallets/kibisis.ts
packages/use-wallet/src/wallets/kmd.ts
packages/use-wallet/src/wallets/lute.ts
packages/use-wallet/src/wallets/magic.ts
packages/use-wallet/src/wallets/mnemonic.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/pera2.ts
packages/use-wallet/src/wallets/walletconnect.ts

See https://forum.algorand.org/t/signtxnsfunction-arc-0001-vs-transactionsigner-algosdk-response-types/12120

feat(core): signTransactions response should match length of txnGroup

---

packages/use-wallet/src/__tests__/utils.test.ts
packages/use-wallet/src/utils.ts

In a controlled test environment using `instanceof` to verify a transaction is of type `algosdk.Transaction` works, but in a production setting a more "low tech" type guard is necessary.
Now the items (either a normal transaction object or encoded transaction) are checked for a `genesisID` property, which confirms it is an unencoded object.

fix(core): fixes isTransactionArray utility function

---

packages/use-wallet/package.json
pnpm-lock.yaml

- moves algosdk to peerDependency
- allows for ^2.7.0 version matching
- resolves #192

fix: move algosdk to peer

---

examples/nextjs/package.json
examples/nuxt/package.json
examples/react-ts/package.json
examples/solid-ts/package.json
examples/vanilla-ts/package.json
examples/vue-ts/package.json
packages/use-wallet-react/package.json
packages/use-wallet-solid/package.json
packages/use-wallet-vue/package.json
packages/use-wallet/package.json
pnpm-lock.yaml

While PR https://github.com/TxnLab/use-wallet/pull/193 moved `algosdk` to `peerDependencies` to ensure the library uses the same version as the consuming application, it also needed to be added to `devDependencies` in the core library to make it available in development.
This also updates all of the example apps and packages to use the same (latest) version, `2.8.0`.

chore: add algosdk to devDependencies, sync versions

---

packages/use-wallet-react/src/index.tsx
packages/use-wallet-solid/src/index.tsx
packages/use-wallet-vue/src/__tests__/useWallet.test.ts
packages/use-wallet-vue/src/useWallet.ts
packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/manager.ts

This reverts a feature that was added in https://github.com/TxnLab/use-wallet/pull/187 where any connected wallets would be disconnected when switching networks.
Some wallets will not work until you reconnect on the new network, but it should be the app's decision how to handle this.
The `WalletManager` still exposes a public `disconnect` method if this is the desired behavior.

fix: switching networks should not disconnect wallets

---

packages/use-wallet-solid/src/__tests__/index.test.tsx
packages/use-wallet-solid/src/index.tsx
packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/__tests__/store.test.ts
packages/use-wallet/src/store.ts

Added algodClient to the store in the core package and modified the SolidJS package to set this property on the store when network is changed. Now useWallet provides a reactive algodClient via the store rather than a signal, which was not behaving reactively before.

feat: reactive algodClient for SolidJS

---

packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/kibisis.ts
packages/use-wallet/src/wallets/lute.ts
packages/use-wallet/src/wallets/magic.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/pera2.ts
packages/use-wallet/src/wallets/walletconnect.ts

This PR addresses an issue where Webpack's static analysis was attempting to resolve all potential dynamic imports at build time, causing "module not found" errors for optional dependencies that weren't installed.
Adding the [magic comment](https://webpack.js.org/api/module-methods/#magic-comments) `/* webpackIgnore: true */` to all dynamic imports in the core library tells Webpack to ignore these imports during its static analysis phase.
This resolves "module not found" errors for uninstalled optional dependencies in consuming applications with Webpack build systems, particularly Next.js.

fix(core): fix Webpack static analysis issue with dynamic imports

---

examples/nextjs/next.config.mjs

This PR addresses the "module not found" errors that occur when using `@txnlab/use-wallet-react` in Next.js applications. These errors were caused by Webpack attempting to resolve optional wallet dependencies, even when they weren't installed or used in the project.
The [first attempt](https://github.com/TxnLab/use-wallet/pull/211) to resolve these errors in the library itself appeared in https://github.com/TxnLab/use-wallet/releases/tag/v3.1.1. It introduced another error and had to be reverted in https://github.com/TxnLab/use-wallet/releases/tag/v3.1.2.
- Updated the Next.js example in the monorepo to include a Webpack configuration that provides fallbacks for optional wallet dependencies.
- The solution uses Webpack's `resolve.fallback` configuration to provide empty modules for …

fix(nextjs): resolve Webpack "module not found" errors

---

packages/use-wallet/src/__tests__/store.test.ts
packages/use-wallet/src/store.ts

This PR addresses the bug described in issue #219, where store mutation functions were inadvertently modifying state in unexpected ways. The fix ensures that the `setActiveAccount`, `addWallet`, and `setAccounts` functions create new object references for nested state properties, preventing unintended mutations of the original state.
- Refactored `setActiveAccount`, `addWallet`, and `setAccounts` to create new object references for nested state properties (wallet state, accounts array, active account).
- Added unit tests to verify the fixes and ensure no unintended state mutations occur.
- These changes prevent unexpected behavior and potential loss of account information that could result from modifying shared object references.
Closes #219

fix(core): immutable state updates in store mutation functions

---

packages/use-wallet-solid/src/index.tsx
packages/use-wallet-vue/src/__tests__/useWallet.test.ts
packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/__tests__/store.test.ts
packages/use-wallet/src/manager.ts
packages/use-wallet/src/store.ts

This is to address issue #213 
- replaced the `algodClient` prop on the `WalletManager` with a getter and setter that point to the `store`
- removed `algodClient` from persisted storage - the re-serialization makes it useless anyway
- `setActiveNetwork` on `store` now takes `algodClient` as a parameter
- tests were updated to reflect the changes

feat: move the algod client to store

---

packages/use-wallet/src/store.ts

This PR updates the import of `Algodv2` from `algosdk` in `src/store.ts` to resolve a SyntaxError occurring in some consuming applications that use CommonJS modules.
- Changed the import of `algosdk` from named import to default import
- Updated all references to `Algodv2` to use the default import syntax
- Resolves the error: "SyntaxError: Named export 'Algodv2' not found. The requested module 'algosdk' is a CommonJS module, which may not support all module.exports as named exports."
Closes #216

fix(core): update algosdk import to resolve CommonJS module issue

---

packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/manager.ts

This PR enhances the `WalletManager` by introducing an `options` object in its configuration. The first option implemented is `resetNetwork`, which allows users to reset the network to the configured value on each initialization, overriding any persisted network state.
- Added `options` object to `WalletManagerConfig` interface
- Implemented `resetNetwork` as the first option in the `options` object
- Updated `WalletManager` constructor to handle the `resetNetwork` option
- Added and updated tests to cover the new `resetNetwork` behavior
- Ensured backward compatibility with existing configurations
This change provides a flexible framework for adding more configuration options in the future, while addressing the immediate need for network reset functionality. The `resetNetwork` option, …

feat: add resetNetwork option to WalletManager

---

packages/use-wallet/src/wallets/kibisis.ts

i faced the same issue as in #203 the issue is that the import in vuejs has the default, so fixed it the same way as it is done in defly f.e.

fix Kibisis init in vue app #203

---

packages/use-wallet/src/index.ts
packages/use-wallet/src/manager.ts

This PR fixes an issue where the `DEBUG` log level was not being properly handled in the `WalletManager` in #264 resulting in `DEBUG` logs not being output as expected. It also includes some refactoring and improvements to the logger initialization process.
- Refactored logger initialization in `WalletManager` to correctly handle all log levels, including `LogLevel.DEBUG`
- Added `WalletManagerOptions` interface for improved type safety and clarity
- Improved log level determination logic to ensure correct handling of all possible inputs
- Exported `WalletManagerOptions` from index.ts for external use

fix: correct DEBUG log level handling in WalletManager

---

examples/nextjs/package.json
examples/nuxt/package.json
examples/react-ts/package.json
examples/solid-ts/package.json
examples/vanilla-ts/package.json
examples/vue-ts/package.json
packages/use-wallet-react/package.json
packages/use-wallet-solid/package.json
packages/use-wallet-vue/package.json
packages/use-wallet/package.json
pnpm-lock.yaml

Update `lute-connect` from `1.3.0` to `1.4.1` to prepare for browser extension.

chore(deps): update lute-connect to v1.4.1

---

packages/use-wallet/src/__tests__/wallets/defly.test.ts
packages/use-wallet/src/__tests__/wallets/pera.test.ts
packages/use-wallet/src/__tests__/wallets/pera2.test.ts
packages/use-wallet/src/wallets/base.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/pera2.ts

This PR fixes the disconnect event handling for Pera and Defly wallets. It addresses an issue where the wallet state wasn't updating correctly when a session was deleted in the mobile app.
- Implemented disconnect event listener registration in `connect` method
- Added proper handling of disconnect events to update the wallet store
- Updated test suites for Pera and Defly wallets to cover disconnect scenarios
- Ensured compatibility with Pera Connect v1 and v2 (beta) implementations
- Refactored mock structures in tests to accurately represent wallet interfaces
This fix improves wallet connection management reliability, especially when disconnecting from the mobile app. Users will now see the correct wallet state in their applications after external disconnection.
Closes #271

fix(wallets): correct disconnect handling for Pera and Defly

---

packages/use-wallet/src/__tests__/wallets/lute.test.ts

This PR updates the `LuteWallet` tests to work with the latest version of `lute-connect`, which now includes browser extension support. The changes improve test coverage and refactor the mocking strategy to isolate tests from the global `window` object.
- Updated mocking strategy for `lute-connect` to handle browser extension support
- Refactored tests to avoid reliance on the global `window` object
- Improved test coverage for `LuteWallet` class
- Ensured compatibility with the latest version of `lute-connect`
- Fixed failing tests caused by the `lute-connect` upgrade

test(lute): update mocking for lute-connect compatibility

---

packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/__tests__/wallets/custom.test.ts
packages/use-wallet/src/__tests__/wallets/defly.test.ts
packages/use-wallet/src/__tests__/wallets/exodus.test.ts
packages/use-wallet/src/__tests__/wallets/kibisis.test.ts
packages/use-wallet/src/__tests__/wallets/kmd.test.ts
packages/use-wallet/src/__tests__/wallets/lute.test.ts
packages/use-wallet/src/__tests__/wallets/magic.test.ts
packages/use-wallet/src/__tests__/wallets/mnemonic.test.ts
packages/use-wallet/src/__tests__/wallets/pera.test.ts
packages/use-wallet/src/__tests__/wallets/pera2.test.ts
packages/use-wallet/src/__tests__/wallets/walletconnect.test.ts
packages/use-wallet/src/storage.ts
packages/use-wallet/src/wallets/base.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/pera.ts

This PR fixes the WalletConnect session management for Defly and Pera wallets, addressing the issues with session persistence and wallet switching described in issue #274. It implements a more robust approach to backing up and restoring WalletConnect sessions, resolving the problems with lost connections and improving overall wallet management reliability.
- Added `manageWalletConnectSession` method to `BaseWallet` class for centralized session management
- Updated `connect`, `disconnect`, and `setActive` methods in Defly and Pera (v1) wallet classes to use the new session management approach
- Implemented proper session backup and restoration when switching between wallets
- Added a delay after `client.disconnect()` to prevent race conditions
- Updated and expanded test cases to cover …

feat(wallets): add WalletConnect v1 session management

---

packages/use-wallet/src/store.ts

I haven't encountered a bug this gnarly in a while. 🤣
The circular import: `src/wallets/mnemonic` imports `src/store`, which imports a few types from `src/wallets`. The `src/wallets/mnemonic` is still loaded when `src/store` imports `src/wallet` despite nothing from `src/wallets/mnemonic` being used.
In short, `src/wallets/mnemonic` imports `src/store`, which indirectly imports `src/wallets/mnemonic`.
This circular import caused an odd issue where the persisted mnemonic had "undefined_mnemonic" as the key in localStorage because `LOCAL_STORAGE_KEY` constant (defined in `src/store.ts` before building the package) was used before it was defined in the `dist/index.js` build output file. The bundler got confused by the circular import and put the modules in the resulting `dist/index.js` in …

fix(core): remove circular import in store.ts & MnemonicWallet

---

packages/use-wallet/src/__tests__/wallets/walletconnect.test.ts
packages/use-wallet/src/wallets/walletconnect.ts

This PR enhances the `WalletConnect` class by implementing an `activeChainId` getter to dynamically determine the correct CAIP-2 chain ID based on the active network. The `connect` and `signTransactions` methods have been updated to use this getter, ensuring that only the chain ID for the currently active network is included in session proposals and transaction signing requests.
- Added `activeChainId` getter to `WalletConnect` class
- Removed `this.chains` property from `WalletConnect` class
- Updated `connect` method to use `activeChainId` in `requiredNamespaces`
- Updated `signTransactions` method to use `activeChainId`
- Removed `chains` parameter from `WalletConnectModal` initialization
- Added tests for `activeChainId` getter and its usage in `connect` and `signTransactions` methods …

fix(walletconnect): use active network chain ID only

---

packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/pera.ts

This PR refines the WalletConnect session management fix implemented in PR #275. It addresses an oversight where backups were being created for all wallet types, not just Defly and Pera which use WalletConnect v1.
- Updated `setActive` method in `DeflyWallet` to only backup Pera wallet sessions
- Updated `setActive` method in `PeraWallet` to only backup Defly wallet sessions
- Ensured WalletConnect sessions are only backed up for relevant wallets (Defly and Pera)
These changes further improve the reliability of wallet switching, ensuring that WalletConnect sessions are managed correctly only for the wallets that require it.
This PR is part of the ongoing fix for issue #274, further refining the solution to the WalletConnect session management problems.

fix(wallet): limit WalletConnect backup to Defly and Pera

---

examples/nextjs/next.config.mjs
packages/use-wallet/src/index.ts
packages/use-wallet/src/webpack.ts

This PR introduces a `webpackFallback` object to handle optional wallet dependencies in Next.js applications using `@txnlab/use-wallet`. This allows applications to build without these packages installed, enabling users to include only the wallet packages they need.
- Add `webpackFallback` object in `src/webpack.ts`
- Export `webpackFallback` from the main `src/index.ts` file
- Update Next.js example app to use the new `webpackFallback`
This change simplifies the configuration process for Next.js applications and ensures that the fallback configuration is maintained within the `@txnlab/use-wallet` library, making it easier to keep up-to-date as new optional dependencies are added.

feat(webpack): add fallback for optional wallet dependencies

---

.github/workflows/ci.yml

Updates CI workflow to run on the new `v4` branch, ensuring all PRs and pushes are properly validated.
- Add `v4` branch to both `pull_request` and `push` triggers in CI workflow
- Ensures code quality checks run on all changes targeting the upcoming major version

chore(ci): add v4 branch to workflow triggers

---

examples/nextjs/src/app/providers.tsx
examples/nuxt/plugins/walletManager.client.ts
examples/react-ts/src/App.tsx
examples/solid-ts/src/App.tsx
examples/vanilla-ts/src/main.ts
examples/vue-ts/src/main.ts
packages/use-wallet/src/__tests__/wallets/defly-web.test.ts
packages/use-wallet/src/__tests__/wallets/kibisis.test.ts
packages/use-wallet/src/utils.ts
packages/use-wallet/src/wallets/avm-web-provider.ts
packages/use-wallet/src/wallets/defly-web.ts
packages/use-wallet/src/wallets/types.ts

This PR migrates the Defly Web provider implementation from #256 to the v4 architecture, adapting it to work with the new network configuration system and `algosdk` v3. See the [original PR](https://github.com/TxnLab/use-wallet/pull/256) for details about the initial Defly Web provider implementation, which will be closed in favor of this v4-compatible version.
It also improves type safety across AVM provider tests by removing `@ts-nocheck` comments and introducing proper TypeScript patterns.
- Update Defly Web provider to use new network configuration builder
- Adapt transaction signing to use `algosdk` v3 API
- Fix genesis hash handling with network config fallback
- Remove `@ts-nocheck` comments from AVM provider tests
- Add type-safe utility types for testing protected methods
- …

feat: add Defly Web extension wallet provider

---

packages/use-wallet/src/wallets/kmd.ts

fix(kmd): prompt for password twice when the password is an empty string
When using KMD wallet for localnet, it's common that the password is set to an empty string. In this case, the memoised logic failed to detect the existing password.
To fix this:
- the password field is initialised to null
- the memoised logic returns the password if it is not null

fix(kmd): handle empty password correctly in getPassword

---

packages/use-wallet/src/__tests__/wallets/kmd.test.ts

This PR adds test coverage for the `KmdWallet` client's password handling functionality, specifically for the empty string and null password handling changes introduced in PR #318.
- Add test to verify empty string passwords are properly cached and reused
- Add test to verify cancelled password prompts (null) fall back to empty string
- Verify password prompt is only shown once when password is cached

test(kmd): add tests for empty and null password handling

---

packages/use-wallet/src/__tests__/wallets/kmd.test.ts
packages/use-wallet/src/__tests__/wallets/mnemonic.test.ts
packages/use-wallet/src/wallets/kmd.ts
packages/use-wallet/src/wallets/mnemonic.ts

There are scenarios where customising window.prompt are needed:
- There are environments where window.prompt isn't supported, for example, Tauri app built for macOS
- a better UI to display the message is required
To implement this change:
- add options to customise the prompt to KMD and Mnemonic wallets
- when the option isn't set, fallback to the default window.prompt

feat(*): add custom password prompt for KMD and Mnemonic

---

packages/use-wallet/src/__tests__/wallets/pera.test.ts
packages/use-wallet/src/__tests__/wallets/pera2.test.ts
packages/use-wallet/src/wallets/pera.ts
packages/use-wallet/src/wallets/pera2.ts

This PR adds automatic connection functionality for Pera wallet when running in the Pera Discover browser environment. The auto-connect happens during session resumption to ensure SSR compatibility and respect existing wallet connections.
- Added auto-connect detection for Pera Discover browser during session resumption
- Added check to prevent auto-connect when another wallet is already active
- Implemented silent error handling for auto-connect attempts
- Added logging for both successful and failed connection attempts
- Added comprehensive test coverage for auto-connect scenarios

feat(pera): add auto-connect for Pera Discover browser

---

packages/use-wallet/src/__tests__/wallets/defly.test.ts
packages/use-wallet/src/__tests__/wallets/pera.test.ts
packages/use-wallet/src/wallets/defly.ts
packages/use-wallet/src/wallets/pera.ts

This PR fixes an issue where inactive WalletConnect v1 wallets (Pera/Defly) would overwrite the active wallet's connected accounts during session resume. The fix skips the `reconnectSession` call for inactive wallets since the library already handles wallet state persistence.
- Skip `reconnectSession` for inactive Pera/Defly wallets
- Prevent WalletConnect v1 storage key collision between Pera and Defly wallets
- Add test coverage to verify fix

fix(wallets): prevent WalletConnect v1 session data collision

---

.gitignore
docs/fundamentals/supported-wallets.md
docs/guides/end-to-end-testing.md
examples/e2e-tests/FakeAlgodResponses.ts
examples/e2e-tests/example.spec.ts
examples/nextjs/package.json
examples/nextjs/playwright.config.ts
examples/nextjs/src/app/providers.tsx
examples/nuxt/package.json
examples/nuxt/playwright.config.ts
examples/nuxt/plugins/walletManager.client.ts
examples/react-ts/package.json
examples/react-ts/playwright.config.ts
examples/react-ts/src/App.tsx
examples/solid-ts/package.json
examples/solid-ts/playwright.config.ts
examples/solid-ts/src/App.tsx
examples/vanilla-ts/package.json
examples/vanilla-ts/playwright.config.ts
examples/vanilla-ts/src/main.ts
examples/vue-ts/package.json
examples/vue-ts/playwright.config.ts
examples/vue-ts/src/main.ts
package.json
pnpm-lock.yaml

- Add guide for end-to-end (E2E) testing using the Mnemonic wallet provider
- Add example Playwright test, which can be used for any of the examples
- Add Playwright configuration for each example

test(e2e): add examples and docs for end-to-end testing

---

docs/guides/react-quick-start.md
packages/use-wallet-react/src/index.tsx

Added the `isReconnecting` state returned by `useWallet` in the react library.
This new state lets users know when a reconnect attempt is in progress.

feat(react): return isReconnecting from useWallet

---

packages/use-wallet-react/src/__tests__/index.test.tsx

This PR fixes React testing warnings by properly handling state updates and effects in the test suite. These warnings occurred because some state updates were happening outside of `act()` wrappers, which React uses to ensure tests run in a way that matches real rendering.
- Make test functions async where needed
- Wrap component renders in `act(async () => {...})`
- Wrap state updates in `act(async () => {...})`
- Add small delays where needed for effects to complete
- Simplify store state change test assertions
- Fix `setActive` and `setActiveAccount` test implementation

test(react): fix React testing warnings with proper act() usage

---

packages/use-wallet-react/src/index.tsx
packages/use-wallet-solid/src/index.tsx
packages/use-wallet-vue/src/useWallet.ts
packages/use-wallet/src/__tests__/manager.test.ts
packages/use-wallet/src/__tests__/network.test.ts
packages/use-wallet/src/manager.ts
packages/use-wallet/src/network.ts
packages/use-wallet/src/store.ts

This PR removes the unused `name` property from network configurations and updates the type signature of `setActiveNetwork` to properly support both built-in and custom network IDs.
⚠️ **BREAKING CHANGE**: The `name` property has been removed from the `NetworkConfig` interface. If you're using custom network configurations, you'll need to remove any `name` properties from your configs.
- Remove unused `name` property from `NetworkConfig` interface
- Remove `name` field from all default network configurations
- Update `setActiveNetwork` to accept both `NetworkId` enum and custom string IDs
- Update type signatures in React, Solid, and Vue adapters
- Update tests to remove name-related assertions

refactor(network): remove name property and improve network ID types

---

packages/use-wallet/src/index.ts

This PR adds the missing export for the `NetworkConfigBuilder` class from the main entry point of the core `use-wallet` package. This class is a key component of the new network configuration API that enables customization of network settings.
- Add `NetworkConfigBuilder` to the main exports in `index.ts`
- Ensures users can access the builder pattern API for network configuration
- Fixes an oversight where this class was implemented but not exposed

fix(core): export NetworkConfigBuilder class

---

docs/README.md
docs/SUMMARY.md
docs/api-reference/usenetwork.md
docs/api-reference/usewallet.md
docs/api-reference/walletmanager.md
docs/framework/react.md
docs/framework/solidjs.md
docs/framework/vue.md
docs/getting-started/configuration.md
docs/getting-started/installation.md
docs/getting-started/supported-wallets.md
docs/guides/connect-wallet-menu.md
docs/guides/custom-provider.md
docs/guides/migrating-from-v3.x.md
docs/guides/runtime-node-configuration.md
docs/guides/signing-transactions.md
docs/guides/switching-networks.md
docs/guides/testing-with-mnemonic-wallet.md
docs/resources/algokit-templates.md
docs/resources/example-projects.md

This PR integrates the v4 documentation from GitBook into the monorepo using GitBook's sync feature. The documentation is synchronized from GitBook ([use-wallet docs](https://txnlab.gitbook.io/use-wallet)) to the `docs` folder in the root of the monorepo.
- Add initial v4 documentation files from GitBook sync
- Configure GitBook sync to commit changes to `gitbook/v4` branch
- Place all documentation Markdown files in the `docs` folder
- Establish foundation for future documentation updates through GitBook sync
- Documentation covers v4.x features including:
- Algorand SDK v3 support
- Runtime node configuration
- Custom networks support
- Framework adapters (React, Vue, SolidJS)

docs(gitbook): sync v4 docs from GitBook

---

docs/getting-started/configuration.md
docs/getting-started/supported-wallets.md
examples/nextjs/package.json
examples/nextjs/src/app/providers.tsx
examples/nuxt/package.json
examples/nuxt/plugins/walletManager.client.ts
examples/react-ts/package.json
examples/react-ts/src/App.tsx
examples/solid-ts/package.json
examples/solid-ts/src/App.tsx
examples/vanilla-ts/package.json
examples/vanilla-ts/src/main.ts
examples/vue-ts/package.json
examples/vue-ts/src/main.ts
packages/use-wallet-react/package.json
packages/use-wallet-solid/package.json
packages/use-wallet-vue/package.json
packages/use-wallet/package.json
packages/use-wallet/src/wallets/lute.ts
pnpm-lock.yaml

`lute-connect` version 1.5.1 grabs the document title rather than requiring the integration to pass in the site name. `siteName` can still be passed optionally, so the change is non-breaking.

lute-connect 1.5.1

---

docs/guides/signing-data.md
examples/nextjs/package.json
examples/nextjs/src/app/Connect.tsx
examples/nuxt/components/Connect.vue
examples/nuxt/package.json
examples/react-ts/package.json
examples/react-ts/src/Connect.tsx
examples/solid-ts/package.json
examples/solid-ts/src/Connect.tsx
examples/vanilla-ts/package.json
examples/vanilla-ts/src/WalletComponent.ts
examples/vue-ts/package.json
examples/vue-ts/src/components/Connect.vue
packages/use-wallet/package.json
packages/use-wallet/src/__tests__/wallets/lute.test.ts
pnpm-lock.yaml

Documentation, examples, and tests for `signData` need to canonize the JSON rather than just stringify it. I published a `canonify` package and implemented it in all the mentioned places.
https://www.npmjs.com/package/canonify

Add `canonify` to signData docs, examples, and tests

---

examples/svelte-ts/package.json
examples/svelte-ts/src/lib/components/connect.svelte
package.json
packages/use-wallet-svelte/package.json
pnpm-lock.yaml

This PR upgrades all Svelte-related packages across the monorepo to resolve compatibility issues between SvelteKit and `@sveltejs/vite-plugin-svelte`. The key upgrade is `@sveltejs/vite-plugin-svelte` from v5.1.0 to v6.1.2, which is required for SvelteKit 2.31.1 compatibility and resolves build errors in the Svelte example project.
- Upgraded `svelte` from 5.35.4 to 5.38.1
- Upgraded `@sveltejs/kit` from 2.22.2 to 2.31.1
- Upgraded `@sveltejs/vite-plugin-svelte` from 5.1.0 to 6.1.2
- Upgraded `@sveltejs/adapter-auto` from 6.0.1 to 6.1.0
- Upgraded `svelte-check` from 4.2.2 to 4.3.1
- Fixed TypeScript error in `Connect` component where `resp.authenticatorData` type was incompatible with `crypto.subtle.digest`
- Ensured all Svelte example projects build successfully with the new package …

feat(svelte): upgrade to Svelte 5.38.1 and SvelteKit 2.31.1
